name: Restarter
version: '${project.version}'
main: de.silentesc.restarter.Main
api-version: '1.20'
authors: [silentesc]
description: 1.20.4 Plugin that restarts the server at a given time

commands:
  restarter_reloadcfg:
    description: Reloads the config
    usage: /restarter_reloadcfg

permissions:
  restarter.reload:
    description: Permission to use /restarter_reloadcfg
    default: op
